services:
  manager:
    image: mysql:9.1.0
    container_name: managersdb
    ports:
      - "3307:3306"
    networks:
      - app-network
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_PASSWORD: mypassword
      MYSQL_USER: myuser
    volumes:
      - manager:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d/:ro

networks:
  app-network:
    driver: bridge

volumes:
  manager: