services:
  managers:
    image: mysql:9.1.0
    container_name: managersdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${MANAGERS_MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MANAGERS_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MANAGERS_MYSQL_PASSWORD}
      MYSQL_USER: ${MANAGERS_MYSQL_USER}
    volumes:
      - manager:/var/lib/mysql
      - ./migrations/auth:/docker-entrypoint-initdb.d/:ro
  
  sessions:
    image: mysql:9.1.0
    container_name: sessionsdb
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: ${SESSIONS_MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${SESSIONS_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${SESSIONS_MYSQL_PASSWORD}
      MYSQL_USER: ${SESSIONS_MYSQL_USER}
    volumes:
      - session:/var/lib/mysql
      - ./migrations/session:/docker-entrypoint-initdb.d/:ro


volumes:
  manager:
  session: